version: "3"
services:
  mongodb:
    image: mongo
    container_name: jogging-app-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - database:/data/db
    ports:
      - 27020:27017
    restart: unless-stopped
    networks:
      - jogging-app-network

  nodejs:
    build: .
    container_name: jogging-app-nodejs
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - jogging-app-network
    depends_on:
      - mongodb
    restart: unless-stopped

networks:
  jogging-app-network:

volumes:
  database:
