name: Jogging app CI

on:
  push:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create env file
      run: |
        touch .env
        echo ACCESS_TOKEN_TTL='10m' >> .env
        echo ACCESS_TOKEN_SECRET_KEY='SvT4hmSMy3GptPScYx3ZCxvYJVrfKuc3' >> .env
    - run: npm ci
    - run: npm test
    - run: npm run build
      env:
        CI: true


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_ACCOUNT_EMAIL}}